### ISSUE TITLE
LDAP-105: SortControlDirContextProcessor not working with JRE 1.5.0.12+

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#144]
["Thomas B":https://jira.spring.io/secure/ViewProfile.jspa?name=thomas.belot](Migrated from ["LDAP-105":https://jira.spring.io/browse/LDAP-105?redirect=false]) said:

Class org.springframework.ldap.control.SortControlDirContextProcessor
is using a static import for two "com.sun._" classes that does not exists anymore in VM 1.5.0.12+ (both moved to "javax.naming.ldap._")

```
   $java com.sun.jndi.ldap.ctl.SortControl
   Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jndi/ldap/ctl/SortControl
```

Workaround is to clean all "com.sun._" import and work with fullreflexivity as partially done with the "JAVA5_RESPONSE_CONTROL" class constant (line 49) for both "javax.naming.ldap._" and "com.sun.*" implementations.

Best regards

Thomas
